-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 17:56:19 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdauditoria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdauditoria` DEFAULT CHARACTER SET utf8 ;
USE `bdauditoria` ;

-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_normativa` 
-- Autor: Abner Portillo
-- Fecha de Creacion: 15/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_normativa` (
  `Pk_Id_normativa` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`Pk_Id_normativa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_proyecto`
-- Autor: Estuardo Perez
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_proyecto` (
  `PK_Id_proyecto` INT NOT NULL,
  `nombre_Proyecto` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `tbl_normativa_Pk_Id_normativa` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Id_proyecto`, `tbl_normativa_Pk_Id_normativa`),
  INDEX `fk_tbl_proyecto_tbl_normativa1_idx` (`tbl_normativa_Pk_Id_normativa` ASC),
  CONSTRAINT `fk_tbl_proyecto_tbl_normativa1`
    FOREIGN KEY (`tbl_normativa_Pk_Id_normativa`)
    REFERENCES `bdauditoria`.`tbl_normativa` (`Pk_Id_normativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_departamentos`
-- Autor: Karina Yos
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_departamentos` (
  `PK_Id_departamentos` INT NOT NULL,
  `nombre_dep` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Id_departamentos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_dominio`
-- Autor: Abner Portillo
-- Fecha de Creacion: 15/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_dominio` (
  `PK_Id_dominio` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `tbl_normativa_Pk_Id_normativa` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Id_dominio`, `tbl_normativa_Pk_Id_normativa`),
  INDEX `fk_tbl_dominio_tbl_normativa1_idx` (`tbl_normativa_Pk_Id_normativa` ASC),
  CONSTRAINT `fk_tbl_dominio_tbl_normativa1`
    FOREIGN KEY (`tbl_normativa_Pk_Id_normativa`)
    REFERENCES `bdauditoria`.`tbl_normativa` (`Pk_Id_normativa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_objetivo`
-- Autor: Abner Portillo
-- Fecha de Creacion: 15/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_objetivo` (
  `PK_Id_Objetivo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `tbl_dominio_PK_Id_dominio` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Id_Objetivo`, `tbl_dominio_PK_Id_dominio`),
  INDEX `fk_tbl_objetivo_tbl_dominio1_idx` (`tbl_dominio_PK_Id_dominio` ASC),
  CONSTRAINT `fk_tbl_objetivo_tbl_dominio1`
    FOREIGN KEY (`tbl_dominio_PK_Id_dominio`)
    REFERENCES `bdauditoria`.`tbl_dominio` (`PK_Id_dominio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_auditores`
-- Autor: Karla Cruz
-- Fecha de Creacion: 15/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_auditores` (
  `Pk_carnet` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `telefono` INT NULL,
  `direccion` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`Pk_carnet`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_asignacionAuditoresaProyecto`
-- Autor: Sindy Batz
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_asignacionAuditoresaProyecto` (
  `Pk_Id_asignacionAuditoresaProyecto` INT NOT NULL,
  `observacion` VARCHAR(45) NULL,
  `PK_Id_proyecto` INT NOT NULL,
  `Pk_carnet` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`Pk_Id_asignacionAuditoresaProyecto`, `PK_Id_proyecto`, `Pk_carnet`),
  INDEX `fk_tbl_asignacionAuditoresaProyecto_tbl_proyecto1_idx` (`PK_Id_proyecto` ASC),
  INDEX `fk_tbl_asignacionAuditoresaProyecto_tbl_auditores1_idx` (`Pk_carnet` ASC),
  CONSTRAINT `fk_tbl_asignacionAuditoresaProyecto_tbl_proyecto1`
    FOREIGN KEY (`PK_Id_proyecto`)
    REFERENCES `bdauditoria`.`tbl_proyecto` (`PK_Id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asignacionAuditoresaProyecto_tbl_auditores1`
    FOREIGN KEY (`Pk_carnet`)
    REFERENCES `bdauditoria`.`tbl_auditores` (`Pk_carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_rubricaEncabezado`
-- Autor: Jazzmin Zavala
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_rubricaEncabezado` (
  `PK_Codrubricae` INT NOT NULL,
  `Documento_rubrica` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Codrubricae`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_recursosTI`
-- Autor: Karina Yoss
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_recursosTI` (
  `Pk_Id_RecursoTi` INT NOT NULL,
  `nombre_Recurso` VARCHAR(45) NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`Pk_Id_RecursoTi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_asignacionRecursosTI`
-- Autor: Sindy Batz
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_asignacionRecursosTI` (
  `PK_Id_asignacionRecursosTI` INT NOT NULL,
  `nombre_recurso` VARCHAR(45) NULL,
  `descripcion_recurso` VARCHAR(45) NULL,
  `Pk_Id_RecursoTi` INT NOT NULL,
  `PK_Id_proyecto` INT NOT NULL,
  `Fk_Codrubricae` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Id_asignacionRecursosTI`, `Pk_Id_RecursoTi`, `PK_Id_proyecto`, `Fk_Codrubricae`),
  INDEX `fk_tbl_asignacionRecursosTI_tbl_proyecto1_idx` (`PK_Id_proyecto` ASC),
  INDEX `fk_tbl_asignacionRecursosTI_tbl_rubrica1_idx` (`Fk_Codrubricae` ASC),
  INDEX `fk_tbl_asignacionRecursosTI_tbl_recursosTI1_idx` (`Pk_Id_RecursoTi` ASC),
  CONSTRAINT `fk_tbl_asignacionRecursosTI_tbl_proyecto1`
    FOREIGN KEY (`PK_Id_proyecto`)
    REFERENCES `bdauditoria`.`tbl_proyecto` (`PK_Id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asignacionRecursosTI_tbl_rubrica1`
    FOREIGN KEY (`Fk_Codrubricae`)
    REFERENCES `bdauditoria`.`tbl_rubricaEncabezado` (`PK_Codrubricae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asignacionRecursosTI_tbl_recursosTI1`
    FOREIGN KEY (`Pk_Id_RecursoTi`)
    REFERENCES `bdauditoria`.`tbl_recursosTI` (`Pk_Id_RecursoTi`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_asignacionDeptoaProyectos`
-- Autor: Karina Yos
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_asignacionDeptoaProyectos` (
  `PK_Idl_asignacionDeptoaProyectos` INT NOT NULL,
  `Descripcion` VARCHAR(45) NULL,
  `tbl_proyecto_PK_Id_proyecto` INT NOT NULL,
  `tbl_departamentos_PK_Id_departamentos` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Idl_asignacionDeptoaProyectos`, `tbl_proyecto_PK_Id_proyecto`, `tbl_departamentos_PK_Id_departamentos`),
  INDEX `fk_tbl_asignacionDeptoaProyectos_tbl_proyecto1_idx` (`tbl_proyecto_PK_Id_proyecto` ASC),
  INDEX `fk_tbl_asignacionDeptoaProyectos_tbl_departamentos1_idx` (`tbl_departamentos_PK_Id_departamentos` ASC),
  CONSTRAINT `fk_tbl_asignacionDeptoaProyectos_tbl_proyecto1`
    FOREIGN KEY (`tbl_proyecto_PK_Id_proyecto`)
    REFERENCES `bdauditoria`.`tbl_proyecto` (`PK_Id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asignacionDeptoaProyectos_tbl_departamentos1`
    FOREIGN KEY (`tbl_departamentos_PK_Id_departamentos`)
    REFERENCES `bdauditoria`.`tbl_departamentos` (`PK_Id_departamentos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_escalanivelentrega`
-- Autor: Jazzmin Zavala
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_escalanivelentrega` (
  `PK_Codescalanivel` INT NOT NULL,
  `Descripcion_escalanivel` VARCHAR(45) NULL,
  `Porcentaje_escalanivel` FLOAT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Codescalanivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_criteriocalificacion`
-- Autor: Jazzmin Zavala
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_criteriocalificacion` (
  `PK_Codcriterioc` INT NOT NULL,
  `Codrubricae` INT NOT NULL,
  `Codescalanivel` INT NOT NULL,
  `estatus` INT NULL,
  PRIMARY KEY (`PK_Codcriterioc`, `Codrubricae`, `Codescalanivel`),
  INDEX `fk_tbl_criteriocalificacion_tbl_rubricaEncabezado1_idx` (`Codrubricae` ASC),
  INDEX `fk_tbl_criteriocalificacion_tbl_escalanivelentrega1_idx` (`Codescalanivel` ASC),
  CONSTRAINT `fk_tbl_criteriocalificacion_tbl_rubricaEncabezado1`
    FOREIGN KEY (`Codrubricae`)
    REFERENCES `bdauditoria`.`tbl_rubricaEncabezado` (`PK_Codrubricae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_criteriocalificacion_tbl_escalanivelentrega1`
    FOREIGN KEY (`Codescalanivel`)
    REFERENCES `bdauditoria`.`tbl_escalanivelentrega` (`PK_Codescalanivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_notarubrica`
-- Autor: Jazzmin Zavala
-- Fecha de Creacion: 18/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_notarubrica` (
  `Codcriterioc` INT NOT NULL,
  `PresoNota_notar` FLOAT NULL,
  `estatus` INT NULL,
  INDEX `fk_tbl_notarubrica_tbl_criteriocalificacion1_idx` (`Codcriterioc` ASC),
  CONSTRAINT `fk_tbl_notarubrica_tbl_criteriocalificacion1`
    FOREIGN KEY (`Codcriterioc`)
    REFERENCES `bdauditoria`.`tbl_criteriocalificacion` (`Codrubricae`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_asignacionAuditorObjetivo`
-- Autor: Karla Cruz
-- Fecha de Creacion: 15/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_asignacionAuditorObjetivo` (
  `PK_FK_Id_proyecto` INT NOT NULL,
  `Pk_FK_carnet` INT NOT NULL,
  `PK_FK_Id_Objetivo` INT NOT NULL,
  INDEX `fk_tbl_asignacionAuditorObjetivo_tbl_asignacionAuditoresaPr_idx` (`PK_FK_Id_proyecto` ASC, `Pk_FK_carnet` ASC),
  INDEX `fk_tbl_asignacionAuditorObjetivo_tbl_objetivo1_idx` (`PK_FK_Id_Objetivo` ASC),
  CONSTRAINT `fk_tbl_asignacionAuditorObjetivo_tbl_asignacionAuditoresaProy1`
    FOREIGN KEY (`PK_FK_Id_proyecto`)
    REFERENCES `bdauditoria`.`tbl_asignacionAuditoresaProyecto` (`PK_Id_proyecto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
 CONSTRAINT `fk_tbl_asignacionAuditorObjetivo_tbl_asignacionAuditoresaProy2`
    FOREIGN KEY (`Pk_FK_carnet`)
    REFERENCES `bdauditoria`.`tbl_asignacionAuditoresaProyecto` (`Pk_carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_asignacionAuditorObjetivo_tbl_objetivo1`
    FOREIGN KEY (`PK_FK_Id_Objetivo`)
    REFERENCES `bdauditoria`.`tbl_objetivo` (`PK_Id_Objetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_subobjetivo`
-- Autor: Sebastian Recinos
-- Fecha de Creacion: 17/10/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_subobjetivo` (
  `PK_ID_Subobjetivo` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  `tbl_objetivo_PK_Id_Objetivo` INT NOT NULL,
  `tbl_auditores_Pk_carnet` INT NOT NULL,
  `estatus` VARCHAR(45) NULL,
  PRIMARY KEY (`PK_ID_Subobjetivo`, `tbl_objetivo_PK_Id_Objetivo`, `tbl_auditores_Pk_carnet`),
  INDEX `fk_tbl_subobjetivo_tbl_auditores1_idx` (`tbl_auditores_Pk_carnet` ASC),
  INDEX `fk_tbl_subobjetivo_tbl_objetivo1_idx` (`tbl_objetivo_PK_Id_Objetivo` ASC),
  CONSTRAINT `fk_tbl_subobjetivo_tbl_auditores1`
    FOREIGN KEY (`tbl_auditores_Pk_carnet`)
    REFERENCES `bdauditoria`.`tbl_auditores` (`Pk_carnet`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tbl_subobjetivo_tbl_objetivo1`
    FOREIGN KEY (`tbl_objetivo_PK_Id_Objetivo`)
    REFERENCES `bdauditoria`.`tbl_objetivo` (`PK_Id_Objetivo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `bdauditoria` ;

-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_modulos`
-- Autor: Hugo Jimenez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_modulos` (
  `PK_Modulo_codigo` INT(11) NOT NULL,
  `modulo_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Modulo_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_aplicacion`
-- Autor: Abner Juarez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_aplicacion` (
  `PK_Api_codigo` INT(11) NOT NULL,
  `api_descripcion` VARCHAR(45) NOT NULL,
  `FK_Codigo_modulo` INT(11) NOT NULL,
  `estatus` INT(2) NOT NULL,
  PRIMARY KEY (`PK_Api_codigo`),
  INDEX `aplicacion_modulo_modulo_codigo_fk` (`FK_Codigo_modulo` ASC),
  CONSTRAINT `aplicacion_modulo_modulo_codigo_fk`
    FOREIGN KEY (`FK_Codigo_modulo`)
    REFERENCES `bdauditoria`.`tbl_modulos` (`PK_Modulo_codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_usuarios`
-- Autor: Hugo Jimenez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_usuarios` (
  `PK_Usu_Codigo` INT(11) NOT NULL,
  `usu_nickname` VARCHAR(45) NULL DEFAULT NULL,
  `usu_password` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Usu_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_bitacora`
-- Autor: Hugo Jimenez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_bitacora` (
  `PK_Bitacora_Correlativo` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_Usuario_Codigo` INT(11) NOT NULL,
  `Nombre_Usu_Bit` VARCHAR(45) NULL DEFAULT NULL,
  `host` VARCHAR(35) NULL DEFAULT NULL,
  `num_aplicacion` INT(11) NOT NULL,
  `accion` VARCHAR(35) NULL DEFAULT NULL,
  `hora` TIME NULL DEFAULT NULL,
  `fecha` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Bitacora_Correlativo`),
  INDEX `bitacora_usuario_usuario_codigo_fk` (`FK_Usuario_Codigo` ASC),
  CONSTRAINT `bitacora_usuario_usuario_codigo_fk`
    FOREIGN KEY (`FK_Usuario_Codigo`)
    REFERENCES `bdauditoria`.`tbl_usuarios` (`PK_Usu_Codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 241
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_doc_asociado`
-- Autor: Abner Juarez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_doc_asociado` (
  `PK_Id_Documento` INT(11) NOT NULL,
  `Nombre_doc` VARCHAR(45) NULL DEFAULT NULL,
  `Ruta` VARCHAR(45) NULL DEFAULT NULL,
  `FK_Api_codigo` INT(11) NOT NULL,
  `status` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_Id_Documento`, `FK_Api_codigo`),
  UNIQUE INDEX `id_documento` (`PK_Id_Documento` ASC),
  INDEX `fk_Doc_asociado_aplicacion1_idx` (`FK_Api_codigo` ASC),
  CONSTRAINT `fk_Doc_asociado_aplicacion1`
    FOREIGN KEY (`FK_Api_codigo`)
    REFERENCES `bdauditoria`.`tbl_aplicacion` (`PK_Api_codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_perfil_encabezado`
-- Autor: Abner Juarez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_perfil_encabezado` (
  `PK_perf_cod_encabezado` INT(11) NOT NULL,
  `perf_nombre` VARCHAR(45) NULL DEFAULT NULL,
  `estatus` INT(2) NULL DEFAULT NULL,
  PRIMARY KEY (`PK_perf_cod_encabezado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_perfil_detalle`
-- Autor: Abner Juarez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_perfil_detalle` (
  `PK_correlativo` INT(11) NOT NULL AUTO_INCREMENT,
  `FK_perf_cod_encabezado` INT(11) NOT NULL,
  `FK_Api_codigo` INT(11) NOT NULL,
  `ingresar` INT(1) NOT NULL,
  `editar` INT(1) NOT NULL,
  `guardar` INT(1) NOT NULL,
  `borrar` INT(1) NOT NULL,
  `consultar` INT(1) NOT NULL,
  PRIMARY KEY (`PK_correlativo`),
  INDEX `perfil_detalle_perfil_encabezado_perf_cod_encabezado_fk` (`FK_perf_cod_encabezado` ASC),
  INDEX `perfil_detalle_aplicacion_api_codigo_fk` (`FK_Api_codigo` ASC),
  CONSTRAINT `perfil_detalle_aplicacion_api_codigo_fk`
    FOREIGN KEY (`FK_Api_codigo`)
    REFERENCES `bdauditoria`.`tbl_aplicacion` (`PK_Api_codigo`),
  CONSTRAINT `perfil_detalle_perfil_encabezado_perf_cod_encabezado_fk`
    FOREIGN KEY (`FK_perf_cod_encabezado`)
    REFERENCES `bdauditoria`.`tbl_perfil_encabezado` (`PK_perf_cod_encabezado`))
ENGINE = InnoDB
AUTO_INCREMENT = 19
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `bdauditoria`.`tbl_relacion_usuario_perfil`
-- Autor: Hugo Jimenez
-- Fecha de Creacion: 20/09/2019
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdauditoria`.`tbl_relacion_usuario_perfil` (
  `FK_Usu_Codigo` INT(11) NULL DEFAULT NULL,
  `FK_perf_codigo` INT(11) NULL DEFAULT NULL,
  INDEX `relacion_usuario_perfil_usuario_usu_codigo_fk` (`FK_Usu_Codigo` ASC),
  INDEX `relacion_usuario_perfil_perfil_encabezado_perf_cod_encabezado_fk` (`FK_perf_codigo` ASC),
  CONSTRAINT `relacion_usuario_perfil_perfil_encabezado_perf_cod_encabezado_fk`
    FOREIGN KEY (`FK_perf_codigo`)
    REFERENCES `bdauditoria`.`tbl_perfil_encabezado` (`PK_perf_cod_encabezado`),
  CONSTRAINT `relacion_usuario_perfil_usuario_usu_codigo_fk`
    FOREIGN KEY (`FK_Usu_Codigo`)
    REFERENCES `bdauditoria`.`tbl_usuarios` (`PK_Usu_Codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

use bdauditoria;

-- Solicitud cambios [SINDY]
-- Eliminando columna nombre_recurso
ALTER TABLE tbl_asignacionrecursosti DROP COLUMN nombre_recurso; 

-- Solicitud cambios [Karina]
create table tbl_tipoRecursoTI(
PK_Id_TipoRecursoTI int,
nombre_TipoRecursoTI varchar(35),
estatus int,
PRIMARY KEY (PK_Id_TipoRecursoTI) 
);

ALTER TABLE tbl_recursosti add id_tiporecurso int;
ALTER TABLE `bdauditoria`.`tbl_recursosti` 
CHANGE COLUMN `id_tiporecurso` `id_tiporecurso` INT(11) NULL DEFAULT NULL AFTER `nombre_Recurso`;
ALTER TABLE `tbl_recursosti` ADD FOREIGN KEY (id_tipoRecurso) REFERENCES `tbl_tipoRecursoTI` (`PK_Id_TipoRecursoTI`);

